/// secrets.rs — mirrors generate-machine-secrets.sh
///
/// Writes nix/secrets/<env>/<machine>/secrets.nix for each machine in the given env,
/// listing every group/field pair from dogma.yml.
use anyhow::{Context, Result};
use std::path::Path;

use crate::config::DogmaConfig;
use crate::log_dim;

pub fn generate(
  config: &DogmaConfig,
  repo_root: &Path,
  env: &str,
) -> Result<()> {
  let nix_secrets = config.nix.secrets.trim_start_matches("./");
  let secrets_dir = repo_root.join(nix_secrets);

  for (machine_name, machine) in &config.machines {
    let out_dir = secrets_dir.join(env).join(machine_name);
    std::fs::create_dir_all(&out_dir)?;

    let out_file = out_dir.join("secrets.nix");
    let mut content =
      String::from("# auto-generated by dogma — do not edit manually\n{\n");

    for group in &machine.secrets {
      if let Some(fields) = config.secrets.get(group) {
        for (field, leaf) in fields {
          // Only emit object leaves (from:vault / from:infra), not static strings
          if matches!(
            leaf,
            crate::config::SecretLeaf::FromVault { .. }
              | crate::config::SecretLeaf::FromInfra { .. }
          ) {
            content.push_str(&format!("  \"{group}/{field}\" = {{}};\n"));
          }
        }
      }
    }

    content.push_str("}\n");

    std::fs::write(&out_file, &content)
      .with_context(|| format!("failed to write {}", out_file.display()))?;

    log_dim!("secrets written: {}", out_file.display());
  }

  Ok(())
}
